Package: 3proxy
Package: adv-cmds
Package: afpfs-ng
Package: apr
Package: apr-lib
Package: apr-util
Package: apt
Package: apt7
Package: apt7-key
Package: apt7-lib
Package: aptitude
Package: aspell
Package: autoconf
Package: automake
Package: autossh
Package: base
Package: bash
Package: basic-cmds
Package: bc
Package: berkeleydb
Package: bind
Package: bison
Package: bitchx
Package: bootstrap-cmds
Package: bsdiff
Package: bzip2
Package: class-dump
Package: classpath
Package: com.bigboss.patchsafari2
Package: com.chronic-dev.greenpois0n.corona
Package: com.chronic-dev.greenpois0n.rocky-racoon
Package: com.deusty.kissxml
Package: com.evad3rs.evasi0n
Package: com.evad3rs.evasi0n7
Package: com.filippobiga.glyphpatch
Package: com.ih8sn0w-squiffy-winocm.p0sixspwn
Package: com.saurik.afc2d
Package: com.saurik.impactor
Package: com.saurik.impactor
Package: com.saurik.impactor
Package: com.saurik.iphone.cve-2010-1797
Package: com.saurik.iphone.fid
Package: com.saurik.iphone.mamu
Package: com.saurik.iphone.nlnf
Package: com.saurik.iphone.ske
Package: com.saurik.patcyh
Package: com.saurik.patcyh
Package: com.saurik.patcyh
Package: com.saurik.privacy
Package: com.saurik.substrate.safemode
Package: com.saurik.webcycript
Package: com.saurik.webcycript
Package: com.teehanlax.element
Package: com.youmail.ios.voicemail
Package: connect.c
Package: coreutils
Package: coreutils-bin
Package: cpio
Package: csu
Package: curl
Package: cvs
Package: cwidget
Package: cycorder
Package: cycript
Package: cycript
Package: cycript
Package: cycript
Package: cycript
Package: cydget
Package: cydget
Package: cydia
Package: cydia
Package: cydia
Package: cydia-lproj
Package: darwintools
Package: dbus
Package: debianutils
Package: developer-cmds
Package: dict
Package: diffutils
Package: diskdev-cmds
Package: dmg2img
Package: dns2tcp
Package: dpkg
Package: easywakeup.net
Package: ed
Package: expat
Package: faac
Package: faad
Package: fastjar
Package: file
Package: file-cmds
Package: findutils
Package: firefly
Package: firmware-sbin
Package: flac
Package: flex
Package: flite
Package: freecoder.org
Package: gawk
Package: gcrypt
Package: gdata-objectivec-client
Package: gdb
Package: gdbm
Package: gettext
Package: git
Package: glib
Package: gmp
Package: gnupg
Package: gnupg2
Package: gnupth
Package: gnutls
Package: gperf
Package: grep
Package: gzip
Package: hackndev.org
Package: hvkls.dyndns.org
Package: iacces.com
Package: ice
Package: iclarified.com
Package: ifon1.no
Package: ifoneguide.nl
Package: ifonetec.com
Package: imagemagick
Package: indent
Package: inetutils
Package: inputproto
Package: interceptty
Package: io.pangu.fuxiqin9
Package: io.pangu.fuxiqin9
Package: io.pangu.xuanyuansword8
Package: iokittools
Package: iphone-gcc
Package: iphone-java
Package: iphone-notes.de
Package: iphone-python
Package: iphoneislam.com
Package: iphonemod.com.br
Package: iphonemodding.com
Package: iphoneos-bcl
Package: ipkg
Package: irssi
Package: jamvm
Package: javasqlite
Package: jikes
Package: jocstrap
Package: jpeg
Package: kbproto
Package: kext-tools
Package: krb5
Package: lame
Package: ldid
Package: less
Package: libarchive
Package: libarmfp
Package: libassuan
Package: libdict
Package: libffi
Package: libgpg-error
Package: libgpod
Package: libid3tag
Package: libksba
Package: libnet
Package: libnids
Package: libpar2
Package: libpcap
Package: libsamplerate
Package: libsigc++
Package: libstdc++
Package: libvncserver
Package: libxml2
Package: libxml2-dylib
Package: libxml2-lib
Package: lighttpd
Package: links
Package: lsof
Package: lynx
Package: lzma
Package: m4
Package: make
Package: mc
Package: mdnsresponder
Package: metasploit3
Package: minicom
Package: mobilefinder
Package: mobilesubstrate
Package: mobilesubstrate
Package: mobilesubstrate
Package: mobilesubstrate
Package: mobilesubstrate
Package: mobilesubstrate
Package: mobileterminal
Package: mspasov.com
Package: mtr
Package: nail
Package: namedfork.net
Package: nano
Package: ncftp
Package: ncurses
Package: neon
Package: netatalk
Package: netcat
Package: network-cmds
Package: ngircd
Package: ngrep
Package: nmap
Package: nvi
Package: odcctools
Package: ogg
Package: openntpd
Package: openslp
Package: openssh
Package: openssl
Package: org.herf.flux
Package: org.herf.flux
Package: org.thebigboss.repo.icons
Package: p7zip
Package: pam
Package: pam-modules
Package: patch
Package: pcre
Package: php
Package: pincrush
Package: pkg-config
Name: Package Config
Package: png
Package: pngcrush
Package: powermanagement
Package: profile.d
Package: pstree
Package: pthread-stubs
Package: pwncenter.com
Package: pyobjc
Package: python
Package: ranbee.com
Package: rdesktop
Package: readline
Package: rhino
Package: ripdev
Package: rlwrap
Package: rpl
Package: rsync
Package: rtadvd
Package: ruby
Package: rzip
Package: saffron-jailbreak-ipad1.1-8f190
Package: saffron-jailbreak-ipad1.1-8g4
Package: saffron-jailbreak-ipad1.1-8h7
Package: saffron-jailbreak-ipad1.1-8j3
Package: saffron-jailbreak-ipad2.1-8j2
Package: saffron-jailbreak-ipad2.2-8j2
Package: saffron-jailbreak-ipad2.3-8j2
Package: saffron-jailbreak-iphone2.1-8f190
Package: saffron-jailbreak-iphone2.1-8g4
Package: saffron-jailbreak-iphone2.1-8h7
Package: saffron-jailbreak-iphone2.1-8j2
Package: saffron-jailbreak-iphone3.1-8f190
Package: saffron-jailbreak-iphone3.1-8g4
Package: saffron-jailbreak-iphone3.1-8h7
Package: saffron-jailbreak-iphone3.1-8j2
Package: saffron-jailbreak-ipod3.1-8f190
Package: saffron-jailbreak-ipod3.1-8h7
Package: saffron-jailbreak-ipod3.1-8j2
Package: saffron-jailbreak-ipod4.1-8f190
Package: saffron-jailbreak-ipod4.1-8g4
Package: saffron-jailbreak-ipod4.1-8h7
Package: saffron-jailbreak-ipod4.1-8j2
Package: screen
Package: sed
Package: setuptools
Package: sgrep
Package: shell-cmds
Package: slirp
Package: sm
Package: sniffit
Package: socat
Package: sosiphone.com
Package: spidermonkey
Package: sqlite3
Package: sqlite3-dylib
Package: sqlite3-lib
Package: srelay
Package: srt10coupe.de
Package: stealthmac
Package: steffwiz.webs.com
Package: stunnel
Package: subversion
Package: sudo
Package: sword
Package: syslogd
Package: system-cmds
Package: taiguicache
Package: taiguntether83x
Package: tar
Package: tcpdump
Package: tcsh
Package: tiff
Package: top
Package: touch-mania.com
Package: treecc
Package: uicaboodle
Package: uicaboodle.py
Package: uikittools
Package: uikittools
Package: unrar
Package: unzip
Package: urbanfanatics.com
Package: uuid
Package: vbindiff
Package: veency
Package: vfdecrypt
Package: vim
Package: vorbis
Package: weechat
Package: wget
Package: whois
Package: winterboard
Package: winterboard
Package: winterboarder.com
Package: x11
Package: x264
Package: xar
Package: xau
Package: xcb
Package: xcb-proto
Package: xext
Package: xextproto
Package: xeyes
Package: xi
Package: xineramaproto
Package: xml2
Package: xmu
Package: xproto
Package: xpwn
Package: xt
Package: xtrans
Package: zanekills.com
Package: zip
Package: zsh
Package: zuijlen.eu
Package: com.saurik.cyueue
Package: cydialer
Package: cyntact
Package: iwipe
Package: voicemail-forwarder