#!/bin/bash
wget http://apt.saurik.com/debs/3proxy_0.5.3k-2p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/adv-cmds_119-6_iphoneos-arm.deb
wget http://apt.saurik.com/debs/afpfs-ng_0.8.1-2p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/apr_1.3.3-4_iphoneos-arm.deb
wget http://apt.saurik.com/debs/apr-lib_1.3.3-2_iphoneos-arm.deb
wget http://apt.saurik.com/debs/apr-util_1.2.12-5_iphoneos-arm.deb
wget http://apt.saurik.com/debs/apt_1:0-23_iphoneos-arm.deb
wget http://apt.saurik.com/debs/apt7_0.7.25.3-9_iphoneos-arm.deb
wget http://apt.saurik.com/debs/apt7-key_0.7.25.3-3_iphoneos-arm.deb
wget http://apt.saurik.com/debs/apt7-lib_0.7.25.3-16_iphoneos-arm.deb
wget http://apt.saurik.com/debs/aptitude_0.4.11.11-6_iphoneos-arm.deb
wget http://apt.saurik.com/debs/aspell_0.60.6-3p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/autoconf_2.63-1_iphoneos-arm.deb
wget http://apt.saurik.com/debs/automake_1.10.2-1_iphoneos-arm.deb
wget http://apt.saurik.com/debs/autossh_1.4a-2p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/base_1-4_iphoneos-arm.deb
wget http://apt.saurik.com/debs/bash_4.0.44-16_iphoneos-arm.deb
wget http://apt.saurik.com/debs/basic-cmds_48-2p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/bc_1.06-2p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/berkeleydb_4.6.21-5_iphoneos-arm.deb
wget http://apt.saurik.com/debs/bind_9.4.2-4p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/bison_2.4.1-4_iphoneos-arm.deb
wget http://apt.saurik.com/debs/bitchx_1.1-4p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/bootstrap-cmds_60-3p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/bsdiff_4.3-1_iphoneos-arm.deb
wget http://apt.saurik.com/debs/bzip2_1.0.5-8_iphoneos-arm.deb
wget http://apt.saurik.com/debs/class-dump_3.1.2-x-1.0.1-2p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/classpath_0.99-4_iphoneos-arm.deb
wget http://apt.saurik.com/debs/com.bigboss.patchsafari2_2.1.3248-1_iphoneos-arm.deb
wget http://apt.saurik.com/debs/com.chronic-dev.greenpois0n.corona_1.0-8_iphoneos-arm.deb
wget http://apt.saurik.com/debs/com.chronic-dev.greenpois0n.rocky-racoon_1.0-3_iphoneos-arm.deb
wget http://apt.saurik.com/debs/com.deusty.kissxml_0.9.26-1_iphoneos-arm.deb
wget http://apt.saurik.com/debs/com.evad3rs.evasi0n_0.4-1_iphoneos-arm.deb
wget http://apt.saurik.com/debs/com.evad3rs.evasi0n7_0.3_iphoneos-arm.deb
wget http://apt.saurik.com/debs/com.filippobiga.glyphpatch_0.3-1_iphoneos-arm.deb
wget http://apt.saurik.com/debs/com.ih8sn0w-squiffy-winocm.p0sixspwn_1.4-1_iphoneos-arm.deb
wget http://apt.saurik.com/debs/com.saurik.afc2d_1.2_iphoneos-arm.deb
wget http://apt.saurik.com/debs/com.saurik.impactor_0.9.43_iphoneos-arm.deb
wget http://apt.saurik.com/debs/com.saurik.impactor_0.9.18_iphoneos-arm.deb
wget http://apt.saurik.com/debs/com.saurik.impactor_0.9.32_iphoneos-arm.deb
wget http://apt.saurik.com/debs/com.saurik.impactor_0.9.16_iphoneos-arm.deb
wget http://apt.saurik.com/debs/com.saurik.impactor_0.9.15_iphoneos-arm.deb
wget http://apt.saurik.com/debs/com.saurik.impactor_0.9.17_iphoneos-arm.deb
wget http://apt.saurik.com/debs/com.saurik.iphone.cve-2010-1797_1.0.3245-1_iphoneos-arm.deb
wget http://apt.saurik.com/debs/com.saurik.iphone.fid_0.9.3400_iphoneos-arm.deb
wget http://apt.saurik.com/debs/com.saurik.iphone.mamu_2.0.2965-1_iphoneos-arm.deb
wget http://apt.saurik.com/debs/com.saurik.iphone.nlnf_1.0.3389_iphoneos-arm.deb
wget http://apt.saurik.com/debs/com.saurik.iphone.ske_0.9.2973-1_iphoneos-arm.deb
wget http://apt.saurik.com/debs/com.saurik.patcyh_1.0.0_iphoneos-arm.deb
wget http://apt.saurik.com/debs/com.saurik.patcyh_1.2.0_iphoneos-arm.deb
wget http://apt.saurik.com/debs/com.saurik.patcyh_1.0.1_iphoneos-arm.deb
wget http://apt.saurik.com/debs/com.saurik.patcyh_1.1.2_iphoneos-arm.deb
wget http://apt.saurik.com/debs/com.saurik.privacy_0.9.3108-1_iphoneos-arm.deb
wget http://apt.saurik.com/debs/com.saurik.substrate.safemode_0.9.6000_iphoneos-arm.deb
wget http://apt.saurik.com/debs/com.saurik.substrate.safemode_0.9.6001_iphoneos-arm.deb
wget http://apt.saurik.com/debs/com.saurik.substrate.safemode_0.9.5000_iphoneos-arm.deb
wget http://apt.saurik.com/debs/com.saurik.webcycript_0.9.5002_iphoneos-arm.deb
wget http://apt.saurik.com/debs/com.saurik.webcycript_0.9.5003_iphoneos-arm.deb
wget http://apt.saurik.com/debs/com.saurik.webcycript_0.9.5001_iphoneos-arm.deb
wget http://apt.saurik.com/debs/com.teehanlax.element_0.9.46-1_iphoneos-arm.deb
wget http://apt.saurik.com/debs/com.youmail.ios.voicemail_0.9.1-2_iphoneos-arm.deb
wget http://apt.saurik.com/debs/connect.c_0-3p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/coreutils_8.12-13_iphoneos-arm.deb
wget http://apt.saurik.com/debs/coreutils-bin_8.12-9_iphoneos-arm.deb
wget http://apt.saurik.com/debs/cpio_2.9-2p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/csu_232-2_iphoneos-arm.deb
wget http://apt.saurik.com/debs/curl_7.33.0-9_iphoneos-arm.deb
wget http://apt.saurik.com/debs/cvs_1.11.22-3p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/cwidget_0.5.8-2_iphoneos-arm.deb
wget http://apt.saurik.com/debs/cycorder_0.9-6_iphoneos-arm.deb
wget http://apt.saurik.com/debs/cycript_0.9.590_iphoneos-arm.deb
wget http://apt.saurik.com/debs/cycript_0.9.594_iphoneos-arm.deb
wget http://apt.saurik.com/debs/cycript_0.9.593_iphoneos-arm.deb
wget http://apt.saurik.com/debs/cycript_0.9.505_iphoneos-arm.deb
wget http://apt.saurik.com/debs/cycript_0.9.592_iphoneos-arm.deb
wget http://apt.saurik.com/debs/cycript_0.9.503_iphoneos-arm.deb
wget http://apt.saurik.com/debs/cycript_0.9.502_iphoneos-arm.deb
wget http://apt.saurik.com/debs/cydget_0.9.5003_iphoneos-arm.deb
wget http://apt.saurik.com/debs/cydget_0.9.5002_iphoneos-arm.deb
wget http://apt.saurik.com/debs/cydget_0.9.5001_iphoneos-arm.deb
wget http://apt.saurik.com/debs/cydia_1.1.27_iphoneos-arm.deb
wget http://apt.saurik.com/debs/cydia_1.1.30_iphoneos-arm.deb
wget http://apt.saurik.com/debs/cydia_1.1.28_iphoneos-arm.deb
wget http://apt.saurik.com/debs/cydia_1.1.24_iphoneos-arm.deb
wget http://apt.saurik.com/debs/cydia_1.1.26_iphoneos-arm.deb
wget http://apt.saurik.com/debs/cydia_1.1.25_iphoneos-arm.deb
wget http://apt.saurik.com/debs/cydia_1.1.29_iphoneos-arm.deb
wget http://apt.saurik.com/debs/cydia-lproj_1.1.12_iphoneos-arm.deb
wget http://apt.saurik.com/debs/darwintools_1-5_iphoneos-arm.deb
wget http://apt.saurik.com/debs/dbus_1.2.16-1_iphoneos-arm.deb
wget http://apt.saurik.com/debs/debianutils_3.3.3ubuntu1-1p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/developer-cmds_48-2p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/dict_1.9.9-3p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/diffutils_2.8.1-6_iphoneos-arm.deb
wget http://apt.saurik.com/debs/diskdev-cmds_421.7-4_iphoneos-arm.deb
wget http://apt.saurik.com/debs/dmg2img_0-2p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/dns2tcp_0.5.2-2p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/dpkg_1.18.10-12_iphoneos-arm.deb
Homepage: wget http://wiki.debian.org/Teams/Dpkg
wget http://apt.saurik.com/debs/easywakeup.net_0-3_iphoneos-arm.deb
wget http://apt.saurik.com/debs/ed_0.8-2p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/expat_2.0.1-3_iphoneos-arm.deb
wget http://apt.saurik.com/debs/faac_1.26-3p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/faad_2.6.1-3p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/fastjar_0.94-2p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/file_4.23-3_iphoneos-arm.deb
wget http://apt.saurik.com/debs/file-cmds_220.7-3_iphoneos-arm.deb
wget http://apt.saurik.com/debs/findutils_4.2.33-7_iphoneos-arm.deb
wget http://apt.saurik.com/debs/firefly_0.2.4.2-1p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/firmware-sbin_0-1_iphoneos-arm.deb
wget http://apt.saurik.com/debs/flac_1.2.1-2_iphoneos-arm.deb
wget http://apt.saurik.com/debs/flex_2.5.35-5_iphoneos-arm.deb
wget http://apt.saurik.com/debs/flite_1.3-2p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/freecoder.org_0-1_iphoneos-arm.deb
wget http://apt.saurik.com/debs/gawk_3.1.6-2p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/gcrypt_1.4.0-2p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/gdata-objectivec-client_129-1_iphoneos-arm.deb
wget http://apt.saurik.com/debs/gdb_1518-12_iphoneos-arm.deb
wget http://apt.saurik.com/debs/gdbm_1.8.3-1_iphoneos-arm.deb
wget http://apt.saurik.com/debs/gettext_0.17-7_iphoneos-arm.deb
wget http://apt.saurik.com/debs/git_2.8.1-5_iphoneos-arm.deb
wget http://apt.saurik.com/debs/glib_2.20.4-3_iphoneos-arm.deb
wget http://apt.saurik.com/debs/gmp_4.2.2-1_iphoneos-arm.deb
wget http://apt.saurik.com/debs/gnupg_1.4.8-4_iphoneos-arm.deb
wget http://apt.saurik.com/debs/gnupg2_2.0.8-2p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/gnupth_2.0.7-2_iphoneos-arm.deb
wget http://apt.saurik.com/debs/gnutls_2.4.1-1p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/gperf_3.0.4-1_iphoneos-arm.deb
wget http://apt.saurik.com/debs/grep_2.5.4-3_iphoneos-arm.deb
wget http://apt.saurik.com/debs/gzip_1.6-7_iphoneos-arm.deb
wget http://apt.saurik.com/debs/hackndev.org_0-2_iphoneos-arm.deb
wget http://apt.saurik.com/debs/hvkls.dyndns.org_0-1_iphoneos-arm.deb
wget http://apt.saurik.com/debs/iacces.com_0-1_iphoneos-arm.deb
wget http://apt.saurik.com/debs/ice_1.0.4-3_iphoneos-arm.deb
wget http://apt.saurik.com/debs/iclarified.com_0-1_iphoneos-arm.deb
wget http://apt.saurik.com/debs/ifon1.no_0-2_iphoneos-arm.deb
wget http://apt.saurik.com/debs/ifoneguide.nl_0-9_iphoneos-arm.deb
wget http://apt.saurik.com/debs/ifonetec.com_0-1_iphoneos-arm.deb
wget http://apt.saurik.com/debs/imagemagick_6.4.3-6-1p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/indent_2.2.9-3p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/inetutils_1.6-8_iphoneos-arm.deb
wget http://apt.saurik.com/debs/inputproto_1.4.2.1-2_iphoneos-arm.deb
wget http://apt.saurik.com/debs/interceptty_0.6-1_iphoneos-arm.deb
wget http://apt.saurik.com/debs/io.pangu.fuxiqin9_1.1_iphoneos-arm.deb
wget http://apt.saurik.com/debs/io.pangu.fuxiqin9_1.3_iphoneos-arm.deb
wget http://apt.saurik.com/debs/io.pangu.fuxiqin9_1.2_iphoneos-arm.deb
wget http://apt.saurik.com/debs/io.pangu.xuanyuansword8_0.4_iphoneos-arm.deb
wget http://apt.saurik.com/debs/iokittools_76-4p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/iphone-gcc_4.2-20080604-1-8_iphoneos-arm.deb
wget http://apt.saurik.com/debs/iphone-java_1.0.2474-2_iphoneos-arm.deb
wget http://apt.saurik.com/debs/iphone-notes.de_0-2_iphoneos-arm.deb
wget http://apt.saurik.com/debs/iphone-python_1.0.2344-2_iphoneos-arm.deb
wget http://apt.saurik.com/debs/iphoneislam.com_0-1_iphoneos-arm.deb
wget http://apt.saurik.com/debs/iphonemod.com.br_0-1_iphoneos-arm.deb
wget http://apt.saurik.com/debs/iphonemodding.com_0-2_iphoneos-arm.deb
wget http://apt.saurik.com/debs/iphoneos-bcl_0.9.2911-2_iphoneos-arm.deb
wget http://apt.saurik.com/debs/ipkg_0.99.163-2_iphoneos-arm.deb
wget http://apt.saurik.com/debs/irssi_0.8.12-3p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/jamvm_1.5.2-4_iphoneos-arm.deb
wget http://apt.saurik.com/debs/javasqlite_20080130-3_iphoneos-arm.deb
wget http://apt.saurik.com/debs/jikes_1.22-3p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/jocstrap_1.0.2549-8_iphoneos-arm.deb
wget http://apt.saurik.com/debs/jpeg_6b-1_iphoneos-arm.deb
wget http://apt.saurik.com/debs/kbproto_1.0.3-2_iphoneos-arm.deb
wget http://apt.saurik.com/debs/kext-tools_117.4-4_iphoneos-arm.deb
wget http://apt.saurik.com/debs/krb5_1.6.3-5p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/lame_3.98b8-3p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/ldid_1:1.2.1_iphoneos-arm.deb
wget http://apt.saurik.com/debs/less_418-3_iphoneos-arm.deb
wget http://apt.saurik.com/debs/libarchive_2.4.11-2p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/libarmfp_0-2_iphoneos-arm.deb
wget http://apt.saurik.com/debs/libassuan_1.0.2-4_iphoneos-arm.deb
wget http://apt.saurik.com/debs/libdict_0.9-3_iphoneos-arm.deb
wget http://apt.saurik.com/debs/libffi_1:3.0.10-5_iphoneos-arm.deb
wget http://apt.saurik.com/debs/libgpg-error_1.6-2p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/libgpod_0.6.0-1_iphoneos-arm.deb
wget http://apt.saurik.com/debs/libid3tag_0.15.1b-1_iphoneos-arm.deb
wget http://apt.saurik.com/debs/libksba_1.0.2-2_iphoneos-arm.deb
wget http://apt.saurik.com/debs/libnet_1.1.2.1-2_iphoneos-arm.deb
wget http://apt.saurik.com/debs/libnids_1.23-1_iphoneos-arm.deb
wget http://apt.saurik.com/debs/libpar2_0.2-1_iphoneos-arm.deb
wget http://apt.saurik.com/debs/libpcap_1.0.0-5_iphoneos-arm.deb
wget http://apt.saurik.com/debs/libsamplerate_0.1.4-1p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/libsigc++_2.2.3-4_iphoneos-arm.deb
wget http://apt.saurik.com/debs/libstdc++_0-1_iphoneos-arm.deb
wget http://apt.saurik.com/debs/libvncserver_0.9.8.1-7_iphoneos-arm.deb
wget http://apt.saurik.com/debs/libxml2_2.6.32-7_iphoneos-arm.deb
wget http://apt.saurik.com/debs/libxml2-dylib_2.6.32-2_iphoneos-arm.deb
wget http://apt.saurik.com/debs/libxml2-lib_2.6.32-3_iphoneos-arm.deb
wget http://apt.saurik.com/debs/ligwget httpd_1.4.18-7_iphoneos-arm.deb
wget http://apt.saurik.com/debs/links_0.99-4p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/lsof_33-4p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/lynx_2.8.6-4p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/lzma_4.32.7-5_iphoneos-arm.deb
wget http://apt.saurik.com/debs/m4_1.4.10-2p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/make_3.81-2p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/mc_4.6.1-1p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/mdnsresponder_171.4-1p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/metasploit3_3.4-7699-20p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/minicom_2.2-3p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/mobilefinder_55-3_iphoneos-arm.deb
wget http://apt.saurik.com/debs/mobilesubstrate_0.9.6011_iphoneos-arm.deb
wget http://apt.saurik.com/debs/mobilesubstrate_0.9.6110_iphoneos-arm.deb
wget http://apt.saurik.com/debs/mobilesubstrate_0.9.6300_iphoneos-arm.deb
wget http://apt.saurik.com/debs/mobilesubstrate_0.9.6010_iphoneos-arm.deb
wget http://apt.saurik.com/debs/mobilesubstrate_0.9.5101_iphoneos-arm.deb
wget http://apt.saurik.com/debs/mobilesubstrate_0.9.6200_iphoneos-arm.deb
wget http://apt.saurik.com/debs/mobilesubstrate_0.9.6000_iphoneos-arm.deb
wget http://apt.saurik.com/debs/mobilesubstrate_0.9.6101_iphoneos-arm.deb
wget http://apt.saurik.com/debs/mobilesubstrate_0.9.6301_iphoneos-arm.deb
wget http://apt.saurik.com/debs/mobileterminal_364.1-10_iphoneos-arm.deb
wget http://apt.saurik.com/debs/mspasov.com_0-1_iphoneos-arm.deb
wget http://apt.saurik.com/debs/mtr_0.73-1p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/nail_12.4-3_iphoneos-arm.deb
wget http://apt.saurik.com/debs/namedfork.net_0-3_iphoneos-arm.deb
wget http://apt.saurik.com/debs/nano_2.2.6-6_iphoneos-arm.deb
wget http://apt.saurik.com/debs/ncftp_3.2.1-3p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/ncurses_5.7-15_iphoneos-arm.deb
wget http://apt.saurik.com/debs/neon_0.26.4-4_iphoneos-arm.deb
wget http://apt.saurik.com/debs/netatalk_2.0.4-7_iphoneos-arm.deb
wget http://apt.saurik.com/debs/netcat_0.7.1-2p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/network-cmds_307.0.1-7_iphoneos-arm.deb
wget http://apt.saurik.com/debs/ngircd_0.12.1-1p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/ngrep_1.45-2p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/nmap_5.00-6_iphoneos-arm.deb
wget http://apt.saurik.com/debs/nvi_1.81.6-5_iphoneos-arm.deb
wget http://apt.saurik.com/debs/odcctools_286-8_iphoneos-arm.deb
wget http://apt.saurik.com/debs/ogg_1.1.3-2_iphoneos-arm.deb
wget http://apt.saurik.com/debs/openntpd_4.2-2p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/openslp_1.2.1-1p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/openssh_6.7p1-13_iphoneos-arm.deb
wget http://apt.saurik.com/debs/openssl_0.9.8zg-13_iphoneos-arm.deb
wget http://apt.saurik.com/debs/org.herf.flux_0.9984_iphoneos-arm.deb
wget http://apt.saurik.com/debs/org.herf.flux_0.9988_iphoneos-arm.deb
wget http://apt.saurik.com/debs/org.herf.flux_0.9986_iphoneos-arm.deb
wget http://apt.saurik.com/debs/org.thebigboss.repo.icons_1.0.deb
wget http://apt.saurik.com/debs/p7zip_4.57-3p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/pam_32.1-4_iphoneos-arm.deb
wget http://apt.saurik.com/debs/pam-modules_36.1-5_iphoneos-arm.deb
wget http://apt.saurik.com/debs/patch_2.5.4-3p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/pcre_8.30-6_iphoneos-arm.deb
wget http://apt.saurik.com/debs/php_5.2.8-3p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/pincrush_0.9.2-1_iphoneos-arm.deb
wget http://apt.saurik.com/debs/pkg-config_0.23-1p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/png_1.2.24-3_iphoneos-arm.deb
wget http://apt.saurik.com/debs/pngcrush_1.7.10-2_iphoneos-arm.deb
wget http://apt.saurik.com/debs/powermanagement_158.10-1_iphoneos-arm.deb
wget http://apt.saurik.com/debs/profile.d_0-2_iphoneos-arm.deb
wget http://apt.saurik.com/debs/pstree_2.35-1_iphoneos-arm.deb
wget http://apt.saurik.com/debs/pthread-stubs_0.1-2_iphoneos-arm.deb
wget http://apt.saurik.com/debs/pwncenter.com_0-1_iphoneos-arm.deb
wget http://apt.saurik.com/debs/pyobjc_1946-4_iphoneos-arm.deb
wget http://apt.saurik.com/debs/python_2.5.1-5p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/ranbee.com_0-4_iphoneos-arm.deb
wget http://apt.saurik.com/debs/rdesktop_1.6.0-5p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/readline_6.0-8_iphoneos-arm.deb
wget http://apt.saurik.com/debs/rhino_1.6R7-2_iphoneos-arm.deb
wget http://apt.saurik.com/debs/ripdev_0-1_iphoneos-arm.deb
wget http://apt.saurik.com/debs/rlwrap_0.29-2p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/rpl_1.4.0-2p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/rsync_3.0.5-3_iphoneos-arm.deb
wget http://apt.saurik.com/debs/rtadvd_307.0.1-2_iphoneos-arm.deb
wget http://apt.saurik.com/debs/ruby_1.9.2-p0-10_iphoneos-arm.deb
wget http://apt.saurik.com/debs/rzip_2.1-2p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/saffron-jailbreak-iPad1,1-8F190-2.~srk1.deb
wget http://apt.saurik.com/debs/saffron-jailbreak-iPad1,1-8G4-2.~srk1.deb
wget http://apt.saurik.com/debs/saffron-jailbreak-iPad1,1-8H7-2.~srk1.deb
wget http://apt.saurik.com/debs/saffron-jailbreak-iPad1,1-8J3-2.~srk1.deb
wget http://apt.saurik.com/debs/saffron-jailbreak-iPad2,1-8J2-2.~srk1.deb
wget http://apt.saurik.com/debs/saffron-jailbreak-iPad2,2-8J2-2.~srk1.deb
wget http://apt.saurik.com/debs/saffron-jailbreak-iPad2,3-8J2-2.~srk1.deb
wget http://apt.saurik.com/debs/saffron-jailbreak-iPhone2,1-8F190-2.~srk1.deb
wget http://apt.saurik.com/debs/saffron-jailbreak-iPhone2,1-8G4-2.~srk1.deb
wget http://apt.saurik.com/debs/saffron-jailbreak-iPhone2,1-8H7-2.~srk1.deb
wget http://apt.saurik.com/debs/saffron-jailbreak-iPhone2,1-8J2-2.~srk1.deb
wget http://apt.saurik.com/debs/saffron-jailbreak-iPhone3,1-8F190-2.~srk1.deb
wget http://apt.saurik.com/debs/saffron-jailbreak-iPhone3,1-8G4-2.~srk1.deb
wget http://apt.saurik.com/debs/saffron-jailbreak-iPhone3,1-8H7-2.~srk1.deb
wget http://apt.saurik.com/debs/saffron-jailbreak-iPhone3,1-8J2-2.~srk1.deb
wget http://apt.saurik.com/debs/saffron-jailbreak-iPod3,1-8F190-2.~srk1.deb
wget http://apt.saurik.com/debs/saffron-jailbreak-iPod3,1-8H7-2.~srk1.deb
wget http://apt.saurik.com/debs/saffron-jailbreak-iPod3,1-8J2-2.~srk1.deb
wget http://apt.saurik.com/debs/saffron-jailbreak-iPod4,1-8F190-2.~srk1.deb
wget http://apt.saurik.com/debs/saffron-jailbreak-iPod4,1-8G4-2.~srk1.deb
wget http://apt.saurik.com/debs/saffron-jailbreak-iPod4,1-8H7-2.~srk1.deb
wget http://apt.saurik.com/debs/saffron-jailbreak-iPod4,1-8J2-2.~srk1.deb
wget http://apt.saurik.com/debs/screen_4.0.3-4_iphoneos-arm.deb
wget http://apt.saurik.com/debs/sed_4.1.5-8_iphoneos-arm.deb
wget http://apt.saurik.com/debs/setuptools_0.6c7-1_iphoneos-arm.deb
wget http://apt.saurik.com/debs/sgrep_1.92a-3p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/shell-cmds_118-7_iphoneos-arm.deb
wget http://apt.saurik.com/debs/slirp_1.0.17-3p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/sm_1.0.3-3_iphoneos-arm.deb
wget http://apt.saurik.com/debs/sniffit_0.3.7.beta-2_iphoneos-arm.deb
wget http://apt.saurik.com/debs/socat_1.7.1.1-3_iphoneos-arm.deb
wget http://apt.saurik.com/debs/sosiphone.com_0-1_iphoneos-arm.deb
wget http://apt.saurik.com/debs/spidermonkey_1.7.0-4p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/sqlite3_3.5.9-13_iphoneos-arm.deb
wget http://apt.saurik.com/debs/sqlite3-dylib_3.5.9-1_iphoneos-arm.deb
wget http://apt.saurik.com/debs/sqlite3-lib_3.5.9-2_iphoneos-arm.deb
wget http://apt.saurik.com/debs/srelay_0.4.6-2p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/srt10coupe.de_0-3_iphoneos-arm.deb
wget http://apt.saurik.com/debs/stealthmac_0.1-1_iphoneos-arm.deb
wget http://apt.saurik.com/debs/steffwiz.webs.com_0-6_iphoneos-arm.deb
wget http://apt.saurik.com/debs/stunnel_4.26-4p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/subversion_1.4.6-2p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/sudo_1.6.9p12-4p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/sword_1.5.11-1_iphoneos-arm.deb
wget http://apt.saurik.com/debs/syslogd_1.1.1_iphoneos-arm.deb
wget http://apt.saurik.com/debs/system-cmds_433.8-14_iphoneos-arm.deb
wget http://apt.saurik.com/debs/taiguicache_2.1_iphoneos-arm.deb
wget http://apt.saurik.com/debs/taiguntether83x_2.3_iphoneos-arm.deb
wget http://apt.saurik.com/debs/tar_1.29-10_iphoneos-arm.deb
wget http://apt.saurik.com/debs/tcpdump_3.9.8-4_iphoneos-arm.deb
wget http://apt.saurik.com/debs/tcsh_6.15.00-3p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/tiff_3.8.2-2p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/top_39-4_iphoneos-arm.deb
wget http://apt.saurik.com/debs/touch-mania.com_0-1_iphoneos-arm.deb
wget http://apt.saurik.com/debs/treecc_0.3.10-1_iphoneos-arm.deb
wget http://apt.saurik.com/debs/uicaboodle_1.0.2475-2_iphoneos-arm.deb
wget http://apt.saurik.com/debs/uicaboodle.py_1.0.2491-2_iphoneos-arm.deb
wget http://apt.saurik.com/debs/uikittools_1.1.11_iphoneos-arm.deb
wget http://apt.saurik.com/debs/uikittools_1.1.12_iphoneos-arm.deb
wget http://apt.saurik.com/debs/uikittools_1.1.10_iphoneos-arm.deb
wget http://apt.saurik.com/debs/unrar_3.6.8-2p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/unzip_5.52-6_iphoneos-arm.deb
wget http://apt.saurik.com/debs/urbanfanatics.com_0-2_iphoneos-arm.deb
wget http://apt.saurik.com/debs/uuid_1.6.0-2p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/vbindiff_3.0b1-3p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/veency_0.9.3500_iphoneos-arm.deb
wget http://apt.saurik.com/debs/vfdecrypt_0-3p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/vim_7.1-3p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/vorbis_1.2.0-2_iphoneos-arm.deb
wget http://apt.saurik.com/debs/weechat_0.2.6-2p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/wget_1.16-4_iphoneos-arm.deb
wget http://apt.saurik.com/debs/whois_4.7.24-2p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/winterboard_0.9.3918_iphoneos-arm.deb
wget http://apt.saurik.com/debs/winterboard_0.9.3919_iphoneos-arm.deb
wget http://apt.saurik.com/debs/winterboarder.com_0-1_iphoneos-arm.deb
wget http://apt.saurik.com/debs/x11_1.1.3-3_iphoneos-arm.deb
wget http://apt.saurik.com/debs/x264_20080226-2245-3_iphoneos-arm.deb
wget http://apt.saurik.com/debs/xar_1.5.2-1p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/xau_1.0.3-3_iphoneos-arm.deb
wget http://apt.saurik.com/debs/xcb_1.1-3_iphoneos-arm.deb
wget http://apt.saurik.com/debs/xcb-proto_1.1-2_iphoneos-arm.deb
wget http://apt.saurik.com/debs/xext_1.0.2-3_iphoneos-arm.deb
wget http://apt.saurik.com/debs/xextproto_7.0.2-2_iphoneos-arm.deb
wget http://apt.saurik.com/debs/xeyes_1.0.1-3p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/xi_1.1.3-3_iphoneos-arm.deb
wget http://apt.saurik.com/debs/xineramaproto_1.1.2-2_iphoneos-arm.deb
wget http://apt.saurik.com/debs/xml2_0.2-3p_iphoneos-arm.deb
wget http://apt.saurik.com/debs/xmu_1.0.3-3_iphoneos-arm.deb
wget http://apt.saurik.com/debs/xproto_7.0.10-2_iphoneos-arm.deb
wget http://apt.saurik.com/debs/xpwn_1247875200-1_iphoneos-arm.deb
wget http://apt.saurik.com/debs/xt_1.0.4-3_iphoneos-arm.deb
wget http://apt.saurik.com/debs/xtrans_1.0.4-2_iphoneos-arm.deb
wget http://apt.saurik.com/debs/zanekills.com_0-3_iphoneos-arm.deb
wget http://apt.saurik.com/debs/zip_2.32-6_iphoneos-arm.deb
wget http://apt.saurik.com/debs/zsh_4.3.10-4_iphoneos-arm.deb
wget http://apt.saurik.com/debs/zuijlen.eu_0-3_iphoneos-arm.deb
wget http://apt.saurik.com/debs/paid/com.saurik.cyueue_1.1.3_iphoneos-arm.deb
wget http://apt.saurik.com/debs/paid/cydialer_0.9.35_iphoneos-arm.deb
wget http://apt.saurik.com/debs/paid/cyntact_1.4.2-1_iphoneos-arm.deb
wget http://apt.saurik.com/debs/paid/iwipe_1.0-1_iphoneos-api.deb
wget http://apt.saurik.com/debs/paid/voicemail-forwarder_1.03-1_iphoneos-arm.deb