http://down.sandai.net/ThunderVIP/ThunderVIP-ugw.exe
http://plugin.xl7.xunlei.com/7.9/func/xl_ext_chrome_setup.exe
https://storage.googleapis.com/harbor-releases/release-1.4.0/harbor-offline-installer-v1.4.0.tgz
https://github.com/vmware/harbor/releases/download/v1.1.2/harbor-offline-installer-v1.1.2.tgz
https://mirrors.tuna.tsinghua.edu.cn/virtualbox/5.2.8/VirtualBox-5.2.8.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/virtualbox/5.2.8/VirtualBox-5.2.8-121009-Linux_amd64.run
https://mirrors.tuna.tsinghua.edu.cn/virtualbox/5.2.8/VirtualBoxSDK-5.2.8-121009.zip
https://releases.rancher.com/os/latest/rancheros.iso
https://ftp.gnu.org/gnu/automake/automake-1.16.tar.xz
https://packages.gitlab.com/gitlab/gitlab-ee/packages/ubuntu/xenial/gitlab-ee_10.5.3-ee.0_amd64.deb
https://notepad-plus-plus.org/repository/7.x/7.5.4/npp.7.5.4.Installer.x64.exe
https://notepad-plus-plus.org/repository/7.x/7.5.4/npp.7.5.4.bin.x64.7z
