#!/bin/bash
make setup 
cd /spksrc/spk/adminer  && make arch-braswell && make clean
cd /spksrc/spk/beets  && make arch-braswell && make clean
cd /spksrc/spk/bicbucstriim  && make arch-braswell && make clean
cd /spksrc/spk/bitlbee  && make arch-braswell && make clean
cd /spksrc/spk/borgbackup  && make arch-braswell && make clean
cd /spksrc/spk/boxbackup-client  && make arch-braswell && make clean
cd /spksrc/spk/chromaprint  && make arch-braswell && make clean
cd /spksrc/spk/comskip  && make arch-braswell && make clean
cd /spksrc/spk/cops  && make arch-braswell && make clean
cd /spksrc/spk/couchpotatoserver  && make arch-braswell && make clean
cd /spksrc/spk/couchpotatoserver-custom  && make arch-braswell && make clean
cd /spksrc/spk/curaengine  && make arch-braswell && make clean
cd /spksrc/spk/darkstat  && make arch-braswell && make clean
cd /spksrc/spk/ddrescue  && make arch-braswell && make clean
cd /spksrc/spk/debian-chroot  && make arch-braswell && make clean
cd /spksrc/spk/deluge  && make arch-braswell && make clean
cd /spksrc/spk/demoservice  && make arch-braswell && make clean
cd /spksrc/spk/diskutils  && make arch-braswell && make clean
cd /spksrc/spk/dnscrypt  && make arch-braswell && make clean
cd /spksrc/spk/domoticz  && make arch-braswell && make clean
cd /spksrc/spk/duplicity  && make arch-braswell && make clean
cd /spksrc/spk/ejabberd  && make arch-braswell && make clean
cd /spksrc/spk/fdupes  && make arch-braswell && make clean
cd /spksrc/spk/fengoffice  && make arch-braswell && make clean
cd /spksrc/spk/ffmpeg  && make arch-braswell && make clean
cd /spksrc/spk/ffsync  && make arch-braswell && make clean
cd /spksrc/spk/flexget  && make arch-braswell && make clean
cd /spksrc/spk/full-text-rss  && make arch-braswell && make clean
cd /spksrc/spk/gateone  && make arch-braswell && make clean
cd /spksrc/spk/gentoo-chroot  && make arch-braswell && make clean
cd /spksrc/spk/git  && make arch-braswell && make clean
cd /spksrc/spk/git-server  && make arch-braswell && make clean
cd /spksrc/spk/gnupg  && make arch-braswell && make clean
cd /spksrc/spk/haproxy  && make arch-braswell && make clean
cd /spksrc/spk/he853  && make arch-braswell && make clean
cd /spksrc/spk/headphones  && make arch-braswell && make clean
cd /spksrc/spk/headphones-custom  && make arch-braswell && make clean
cd /spksrc/spk/homeassistant  && make arch-braswell && make clean
cd /spksrc/spk/horde  && make arch-braswell && make clean
cd /spksrc/spk/htop  && make arch-braswell && make clean
cd /spksrc/spk/htpcmanager  && make arch-braswell && make clean
cd /spksrc/spk/icecast  && make arch-braswell && make clean
cd /spksrc/spk/imagemagick  && make arch-braswell && make clean
cd /spksrc/spk/irssi  && make arch-braswell && make clean
cd /spksrc/spk/jackett  && make arch-braswell && make clean
cd /spksrc/spk/jappix  && make arch-braswell && make clean
cd /spksrc/spk/jupp  && make arch-braswell && make clean
cd /spksrc/spk/lazylibrarian  && make arch-braswell && make clean
cd /spksrc/spk/links  && make arch-braswell && make clean
cd /spksrc/spk/lirc  && make arch-braswell && make clean
cd /spksrc/spk/ls  && make arch-braswell && make clean
cd /spksrc/spk/mantisbt  && make arch-braswell && make clean
cd /spksrc/spk/maraschino  && make arch-braswell && make clean
cd /spksrc/spk/mc  && make arch-braswell && make clean
cd /spksrc/spk/mediainfo  && make arch-braswell && make clean
cd /spksrc/spk/memcached  && make arch-braswell && make clean
cd /spksrc/spk/mercurial  && make arch-braswell && make clean
cd /spksrc/spk/monit  && make arch-braswell && make clean
cd /spksrc/spk/mono  && make arch-braswell && make clean
cd /spksrc/spk/mosquitto  && make arch-braswell && make clean
cd /spksrc/spk/museek-plus  && make arch-braswell && make clean
cd /spksrc/spk/mutt  && make arch-braswell && make clean
cd /spksrc/spk/mylar  && make arch-braswell && make clean
cd /spksrc/spk/nano  && make arch-braswell && make clean
cd /spksrc/spk/ncdu  && make arch-braswell && make clean
cd /spksrc/spk/nzbget  && make arch-braswell && make clean
cd /spksrc/spk/nzbget-testing  && make arch-braswell && make clean
cd /spksrc/spk/nzbhydra  && make arch-braswell && make clean
cd /spksrc/spk/nzbmegasearch  && make arch-braswell && make clean
cd /spksrc/spk/octoprint  && make arch-braswell && make clean
cd /spksrc/spk/oscam  && make arch-braswell && make clean
cd /spksrc/spk/owncloud  && make arch-braswell && make clean
cd /spksrc/spk/plexivity  && make arch-braswell && make clean
cd /spksrc/spk/plexpy-custom  && make arch-braswell && make clean
cd /spksrc/spk/plowshare  && make arch-braswell && make clean
cd /spksrc/spk/pyload  && make arch-braswell && make clean
cd /spksrc/spk/python  && make arch-braswell && make clean
cd /spksrc/spk/python3  && make arch-braswell && make clean
cd /spksrc/spk/radarr  && make arch-braswell && make clean
cd /spksrc/spk/rdiff-backup  && make arch-braswell && make clean
cd /spksrc/spk/redis  && make arch-braswell && make clean
cd /spksrc/spk/roundcube  && make arch-braswell && make clean
cd /spksrc/spk/rsnapshot  && make arch-braswell && make clean
cd /spksrc/spk/rutorrent  && make arch-braswell && make clean
cd /spksrc/spk/sabnzbd  && make arch-braswell && make clean
cd /spksrc/spk/sabnzbd-testing  && make arch-braswell && make clean
cd /spksrc/spk/salt-master  && make arch-braswell && make clean
cd /spksrc/spk/saltpad  && make arch-braswell && make clean
cd /spksrc/spk/selfoss  && make arch-braswell && make clean
cd /spksrc/spk/shairport-sync  && make arch-braswell && make clean
cd /spksrc/spk/sickbeard-custom  && make arch-braswell && make clean
cd /spksrc/spk/sickrage  && make arch-braswell && make clean
cd /spksrc/spk/sonarr  && make arch-braswell && make clean
cd /spksrc/spk/squidguard  && make arch-braswell && make clean
cd /spksrc/spk/sshfs  && make arch-braswell && make clean
cd /spksrc/spk/sslh  && make arch-braswell && make clean
cd /spksrc/spk/subliminal  && make arch-braswell && make clean
cd /spksrc/spk/syncthing  && make arch-braswell && make clean
cd /spksrc/spk/syncthing-inotify  && make arch-braswell && make clean
cd /spksrc/spk/tcl  && make arch-braswell && make clean
cd /spksrc/spk/testdisk  && make arch-braswell && make clean
cd /spksrc/spk/tmux  && make arch-braswell && make clean
cd /spksrc/spk/transmission  && make arch-braswell && make clean
cd /spksrc/spk/tt-rss  && make arch-braswell && make clean
cd /spksrc/spk/tvheadend  && make arch-braswell && make clean
cd /spksrc/spk/umurmur  && make arch-braswell && make clean
cd /spksrc/spk/vim  && make arch-braswell && make clean
cd /spksrc/spk/wallabag  && make arch-braswell && make clean
cd /spksrc/spk/znc  && make arch-braswell && make clean
cd /spksrc/spk/zsh  && make arch-braswell && make clean
cd /spksrc/spk/zsh-static  && make arch-braswell && make clean
