#!/bin/bash
# Copyright 2017 VMware, Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
HARBORYML="-f /etc/harbor/docker-compose.yml -f /etc/harbor/docker-compose.notary.yml -f /etc/harbor/docker-compose.clair.yml"
# do_prepare() {
	# if [ -f /etc/harbor/harbor.cfg ]; then
	# /etc/harbor/prepare --conf /etc/harbor/harbor.cfg --with-notary --with-clair
	# fi
# }
# do_start() {
# /usr/local/bin/docker-compose -f /etc/harbor/docker-compose.yml \
# -f /etc/harbor/docker-compose.notary.yml \
# -f /etc/harbor/docker-compose.clair.yml up -d
# }
# do_stop() {
# /usr/local/bin/docker-compose -f /etc/harbor/docker-compose.yml \
# -f /etc/harbor/docker-compose.notary.yml \
# -f /etc/harbor/docker-compose.clair.yml down
# }
# do_restart() {
# /usr/local/bin/docker-compose -f /etc/harbor/docker-compose.yml \
# -f /etc/harbor/docker-compose.notary.yml \
# -f /etc/harbor/docker-compose.clair.yml restart
# }
do_prepare() {
	if [ -f /etc/harbor/harbor.cfg ]; then
	/etc/harbor/prepare --conf /etc/harbor/harbor.cfg --with-notary --with-clair
	fi
}
do_start() {
/usr/local/bin/docker-compose $HARBORYML up -d
}
do_stop() {
/usr/local/bin/docker-compose $HARBORYML down
}
do_restart() {
/usr/local/bin/docker-compose $HARBORYML restart
}							  
							  
#!/bin/sh

case $1 in
	prepare)
	do_prepare
        exit 0
        ;;
	start)
    do_start
        exit 0
        ;;
	stop)
    do_stop
        exit 0
        ;;
	restart)
    do_restart
        exit 0
        ;;
    *)
	echo "Invalid input..."
	exit 1
	;;
esac

